create table if not exists baseline (
  id bigint generated by default as identity primary key,
  coverage integer not null default 0,
  communities_reached integer not null default 0,
  critical_areas_served integer not null default 0,
  resource_waste integer not null default 0
);

create table if not exists benefits (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null
);

create table if not exists sources (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  records integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists regions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  needs integer not null default 0,
  volunteers integer not null default 0,
  target_volunteers integer not null default 0,
  focus text not null
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  title text not null,
  detail text not null,
  type text not null,
  created_at timestamptz not null default now()
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  region text not null,
  category text not null,
  priority text not null,
  description text not null,
  people_affected integer not null,
  created_at timestamptz not null default now()
);

create table if not exists donations (
  id bigint generated by default as identity primary key,
  donor_name text not null,
  region text not null,
  category text not null,
  quantity integer not null,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists deployments (
  id bigint generated by default as identity primary key,
  region text not null,
  volunteers integer not null,
  note text not null default '',
  created_at timestamptz not null default now()
);
