-- RahatSetu complete schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- Safe to re-run: uses IF NOT EXISTS

-- Core tables
create table if not exists baseline (
  id bigint generated by default as identity primary key,
  coverage integer not null default 0,
  communities_reached integer not null default 0,
  critical_areas_served integer not null default 0,
  resource_waste integer not null default 0
);

create table if not exists benefits (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null
);

create table if not exists sources (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  records integer not null default 0,
  created_at text not null default ''
);

create table if not exists regions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  needs integer not null default 0,
  volunteers integer not null default 0,
  target_volunteers integer not null default 0,
  focus text not null
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  title text not null,
  detail text not null,
  type text not null,
  created_at text not null default ''
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  region text not null,
  category text not null,
  priority text not null,
  description text not null,
  people_affected integer not null,
  created_at text not null default ''
);

create table if not exists donations (
  id bigint generated by default as identity primary key,
  donor_name text not null,
  region text not null,
  category text not null,
  quantity integer not null,
  notes text not null default '',
  created_at text not null default ''
);

create table if not exists deployments (
  id bigint generated by default as identity primary key,
  region text not null,
  volunteers integer not null,
  note text not null default '',
  created_at text not null default ''
);

-- Users table for authentication
create table if not exists users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password text not null,
  full_name text not null default '',
  role text not null default 'user',
  created_at text not null default ''
);

-- Disable RLS on all tables so the publishable key can read/write
alter table baseline    disable row level security;
alter table benefits    disable row level security;
alter table sources     disable row level security;
alter table regions     disable row level security;
alter table activities  disable row level security;
alter table reports     disable row level security;
alter table donations   disable row level security;
alter table deployments disable row level security;
alter table users       disable row level security;
